version: '3.4'
networks:
  dev-env:
    driver: bridge 

services:
  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://db:5432/web-api-storage -user=bloguser -locations=filesystem:/flyway/sql -password=bloguser -connectRetries=10 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
    networks:
      - dev-env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "bloguser"
      POSTGRES_PASSWORD: "bloguser"
      POSTGRES_DB: "web-api-storage"
    ports:
      - "5433:5432"
    volumes:
      - database_data_volume:/var/lib/postgresql/data
    networks:
      - dev-env
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: web-api/Dockerfile
    depends_on:
      - db
      - flyway
    environment:
      DB_CONNECTION_STRING: "host=db;port=5432;database=web-api-storage;username=bloguser;password=bloguser"
    networks:
      - dev-env
volumes:
  database_data_volume:
  migrations:
