version: '3.4'
networks:
  dev-env:
    driver: bridge 

services:
  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://db:5432/web-api-storage -user=${PG_USER} -locations=filesystem:/flyway/sql -password=${PG_PWD} -connectRetries=10 migrate
    depends_on:
      - db
    volumes:
      - ${MIGRATIONS_PATH}:/flyway/sql 
    networks:
      - dev-env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: "web-api-storage"
    ports:
      - "5432"
    volumes:
      - database_data_volume:/var/lib/postgresql/data
    networks:
      - dev-env
  web-api:
    image: kozyriev/${IMAGE_NAME}
    ports:
      - "0:80"
      - "44338:443"
    depends_on:
      - db
      - flyway
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - DB_CONNECTION_STRING=host=db;port=5432;database=web-api-storage;username=${PG_USER};password=${PG_PWD}
    networks:
      - dev-env
volumes:
  database_data_volume:
