version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore packages
          command: 
            dotnet restore web-api.sln
      - run:
          name: Build app
          command: 
            dotnet build --no-restore web-api.sln
      - run:
          name: Running tests
          command: 
            dotnet test web-api.sln -c Release
  docker-build:
    environment:
      IMAGE_NAME: kozyriev\super-api
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker  
      - run:
          name: Docker image build
          command:
            docker build . -t $IMAGE_NAME:$CIRCLE_BUILD_NUM
  docker-publish:
    environment:
      IMAGE_NAME: kozyriev\super-api
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker  
      - run:
          name: Docker image publish
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_BUILD_NUM

      

workflows:
  version: 2
  pull:
    jobs: 
      - build
          filters:
            branches:
              ignore:
                - master
  commit:
    jobs:
      - docker-build:
          filters:
            branches:
              only: master
      - docker-publish:
          requires:
            - docker-build
          filters:
            branches:
              only: master
